--original dataset
SELECT TOP (1000) [Sale_Date]
      ,[Sales_Year]
      ,[Sales_Month]
      ,[Gallery]
      ,[Artist]
      ,[Orign_Year]
      ,[Length_in]
      ,[Width_in]
      ,[Sale_Price]
  FROM [Portfolio Project].[dbo].[Paintings Sales]


--ordering artists alphabetically and shifting columns for better understanding
  SELECT  [Artist]
      ,[Gallery]      
      ,[Orign_Year]
      ,[Length_in]
      ,[Width_in]
      ,[Sale_Price]
	  ,[Sales_Month]
      ,[Sales_Year]
	  ,[Sale_Date]
  FROM [Portfolio Project].[dbo].[Paintings Sales]
  order by [Artist]


  --yearly number of sales
 select [Sales_Year],
     count ( [Artist]) as "Quantity of Paintings"
	 from [dbo].[Paintings Sales] 
	 group by [Sales_Year]


  --Monthly number of Sales in each year
 select [Sales_Year],[Sales_Month],
        count ( [Artist]) as "Quantity of Paintings"
		from [dbo].[Paintings Sales]
		group by  [Sales_Year],[Sales_Month]



  --the amount of time each artist's paintings were sold
SELECT  Artist, 
    COUNT([Sale_Price]) AS "Number_of_Sales"
FROM [dbo].[Paintings Sales]
GROUP BY [Artist]
ORDER BY Number_of_Sales desc
    

--sales revenue genereated by galleries in each year from highest to lowest
select [Gallery],
       [Sales_Year],
	   SUM([Sale_Price]) as "Revenue"
	   from [dbo].[Paintings Sales]
	   group by [Gallery], [Sales_Year]
	   order by "Revenue" desc 

--pivot table illustrating total sales revenue each yaer aacross galleries
select* from 
(select [Gallery],
       [Sale_Price],
	   [Sales_Year]
	   from [dbo].[Paintings Sales])t

pivot(

sum ([Sale_Price])
FOR [Sales_Year] in ([2007], [2008], [2009], [2010], [2011]) 
) as "pivot"

--Compare galleries sales to see if the revenue only depends on the number of paintings sold
 select [Gallery],
   COUNT([Sale_Price])AS "Number_of_Sales",
   sum([Sale_Price]) as "Revenue"
FROM [dbo].[Paintings Sales]
GROUP BY [Gallery]
ORDER BY Revenue DESC


--Revenue generated by artists
select [Artist],
      sum ([Sale_Price]) as "Revenue"
	  from [dbo].[Paintings Sales]
	  group by [Artist]
	  order by Revenue desc

--Top artists whose total sales exceeded 100000
SELECT Artist, 
   SUM(Sale_Price) AS "Total_Sales"
FROM [dbo].[Paintings Sales]
GROUP BY Artist    
HAVING SUM(Sale_Price) > '100000'



--determine whether the price of the painting is correlated with its size       
select  [Sale_Price],
        CAST(Length_in AS INT) * CAST(Width_in AS INT) AS "Size_of_the_painting_sq.in"
	 from [dbo].[Paintings Sales]
	 order by [Sale_Price] desc 


--Determine if there’s a trend in sale price because of the year in which the artwork was created.
select [Orign_Year],
      SUM([Sale_Price]) as "Total_sales_revenue"
	  
	   from [dbo].[Paintings Sales]
	   group by [Orign_Year]
	   order by [Orign_Year]






       


